import{a as $,S as x,i as B}from"./assets/vendor-Bbadc3Tp.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();async function p(r,t){return(await $.get("https://pixabay.com/api/",{params:{key:"55036420-a7a19d5751e273048ff10c958",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const g=document.querySelector(".loader"),y=document.querySelector(".gallery");let E=new x(".gallery .photo-card a",{captionsData:"alt",captionDelay:250});function L(r){function t(e){const{webformatURL:o,tags:n,likes:b,views:S,comments:P,downloads:q,largeImageURL:D}=e;return`<li class="photo-card">
              <a href=${D}><img src="${o}" alt="${n}"/></a>

              <div class="info">
              <div class="info-item"><h2>Likes: <span>${b}</span></h2></div>
              <div class="info-item"> <h2>Views: <span>${S}</span></h2></div>
              <div class="info-item"><h2>Comments: <span>${P}</span></h2></div>
              <div class="info-item"><h2>Downloads: <span>${q}</span></h2></div>
            </div>
            </li>
            `}function a(e){return e.map(t).join("")}const c=a(r);y.insertAdjacentHTML("beforeend",c),E.refresh()}function O(){y.innerHTML=""}function w(){g.classList.remove("is-hidden")}function d(){g.classList.add("is-hidden")}function R(){m.classList.remove("is-hidden")}function h(){m.classList.add("is-hidden")}function s(r){B.show({message:r,position:"topRight",backgroundColor:"rgba(232, 13, 13, 0.8)",messageColor:"white"})}const u=document.querySelector(".form"),m=document.querySelector(".load"),T=15;let i,l,f;u.addEventListener("submit",C);//! ========================================
async function C(r){if(r.preventDefault(),l=new FormData(u).get("search-text").trim(),l===""){s("Please enter a search term");return}i=1,O(),w(),h();try{const a=await p(l,i);if(f=Math.ceil(a.totalHits/T),!a.hits.length){s("Sorry, there are no images matching your search query.Please try again!");return}L(a.hits),v()}catch(a){console.log(a),s("Something went wrong!")}finally{d(),u.reset()}}//! ========================================
m.addEventListener("click",M);async function M(r){r.preventDefault(),i+=1,w(),h();try{const t=await p(l,i);L(t.hits),F(),v()}catch{d(),s("Something went wrong!")}finally{d()}}function F(){const t=document.querySelector(".photo-card").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}function v(){f&&(i>=f?(s("We're sorry, but you've reached the end of search results."),h()):R())}
//# sourceMappingURL=index.js.map
